### ISSUE TITLE
Install Arsenal driver

### ISSUE THREAD

**Issue by lazychris2000** [tmcdos/ramdisk#3]
It's so much an issue with your software, but I wasn't sure how else to post this so it would hopefully help the next person who runs into problems. Apologies if this is not the correct place for this post.

Since it wasn't mentioned on the link to the Arsenal driver or in the downloaded archive, to install the Arsenal driver, download driversetup.7z, extract the archive, then using an admin command prompt in the root of the extracted folder, do the following:
```
cd cli\<your architecture>
aim_ll.exe --install ..\..
```

You should get something similar to the following output:
```
Detected Windows kernel version 10.0.19045.
Platform code: 'Win10'. Using port driver storport.sys.

Reading inf file...
Creating device object...
Installing driver for device...
Finished successfully.
```

It should automatically detect your windows version and install the appropriate driver.  Afterwards, you should have no problem using RAMdiskUI.exe to install the service and configuring your RAMdisk.

Make sure you point it to the root of the extracted folder.  If you try to point aim_ll.exe to your windows version, it will fail like so:
```
D:\Desktop\DriverSetup\cli\x64>aim_ll.exe --install ..\..\Win10\
Detected Windows kernel version 10.0.19045.
Platform code: 'Win10'. Using port driver storport.sys.

Reading inf file...
Error reading file '..\..\Win10\\Win10\phdskmnt.inf': The system cannot find the path specified.

Setup failed: The system cannot find the path specified.
```

**Comment by tmcdos** [comment]
Thank you, I will add this information to the README.
